version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  airflow:
    build: .
    container_name: crypto_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/crypto_db
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ./src:/opt/src
      - ./data:/opt/data
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db migrate &&
      airflow scheduler &
      exec airflow standalone
      "

volumes:
  postgres_data: